import { Analysis, Channel, ManagedChannel, RadarData, defaultSettings } from './types';

const demoDate = '2026-09-22T12:00:00.000Z';
const opportunities = [
 {id:'first-economy',name:'The First Economy',lens:'Uma aldeia pré-histórica inventa as regras do dinheiro.',promise:'Entender economia acompanhando decisões de sobrevivência.',difference:'Cada episódio constrói uma instituição nova e revela seus efeitos na aldeia.',episodes:['The Village That Invented Debt','Why Saving Food Is Not Enough','The Day Stones Lost Their Value','Who Should Pay for the Bridge?','The First Bank Run'],risk:'A metáfora precisa preservar as limitações do conceito econômico.',test:'Comparar duas promessas de título para o primeiro episódio.'},
 {id:'money-trial',name:'Money on Trial',lens:'Conceitos financeiros sentam no banco dos réus.',promise:'Compreender decisões financeiras ouvindo consequências de lados diferentes.',difference:'O conflito nasce de um julgamento, com evidências e veredito condicionado.',episodes:['Is Debt Guilty?','Interest on Trial','Inflation: Who Took the Money?','The Defendant Called Risk','Saving Versus Spending'],risk:'Evitar simplificações que façam uma resposta parecer universal.',test:'Testar um gancho com acusação e uma thumbnail com um único conflito.'},
 {id:'space-reserve',name:'Starship Reserves',lens:'Tripulantes administram recursos durante uma viagem sem reabastecimento.',promise:'Aprender risco, reserva e investimento através de decisões com consequências.',difference:'O universo impõe escassez e horizontes de tempo diferentes.',episodes:['The Ship That Spent Its Reserves','Plant Today or Eat Tomorrow?','The Price of an Oxygen Tank','Who Guarantees the Loan?','A Portfolio Across the Galaxy'],risk:'A ficção não substitui uma fonte factual.',test:'Validar clareza da metáfora com um piloto de 60 segundos.'},
 {id:'future-museum',name:'The Money Mistakes Museum',lens:'Um curador do futuro reconstrói escolhas do nosso presente.',promise:'Enxergar consequências que passam despercebidas no cotidiano.',difference:'Objetos de museu contam histórias, com reconstituição e comparação.',episodes:['The Relic Called a Credit Card','The Man Who Sold Tomorrow','When Everyone Bought the Same Thing','The Vault That Shrank','The Last Installment'],risk:'Separar claramente cenário fictício de acontecimentos reais.',test:'Testar o interesse por uma série de três objetos cotidianos.'},
 {id:'decision-workshop',name:'The Decision Workshop',lens:'Escolhas financeiras viram máquinas e experiências visuais.',promise:'Ver como uma pequena decisão muda o resultado ao longo do tempo.',difference:'A experiência visual e seus controles ocupam o centro da narrativa.',episodes:['The Small Spending Machine','The Interest Engine','The Gears of Risk','What Does Waiting Cost?','The Inflation Conveyor'],risk:'Experiências ilustrativas não representam previsões de retorno.',test:'Avaliar se o espectador explica o conceito depois de assistir ao piloto.'}
];
function anatomy(niche: string): Analysis {
 return {observation:`Exemplo fictício de um canal de ${niche.toLowerCase()} com personagem e universo recorrentes. Os números desta demonstração não representam um canal real.`,mechanism:'Demanda por compreensão + conflito simples + personagem com ponto de vista + representação visual concreta.',hypotheses:['Um conflito recorrente pode tornar conceitos abstratos mais fáceis de acompanhar.','O universo próprio pode dar ao espectador uma razão para voltar.'],gaps:['Explicar as consequências e os limites das metáforas.','Construir séries em que cada episódio desenvolve o universo.','Mostrar mais de uma decisão possível e seus custos.'],limitations:['Demonstração editorial, sem pesquisa de mercado executada.','Nenhum vídeo ou transcrição real foi analisado.','Não há dados de RPM, CTR ou retenção.'],opportunities: opportunities.map(x=>({...x,episodes:[...x.episodes]})),sources:[],review:'As propostas são hipóteses para investigação. Priorizar clareza da promessa e distância criativa antes de produzir.',createdAt:demoDate};
}
export const demoChannels: Channel[] = [
 {id:'demo-stone',name:'Stone Age Economics',handle:'@exemplo-stone',niche:'Finanças',language:'Inglês',format:'Long form · 2D',description:'Uma aldeia de caçadores tenta entender as regras invisíveis do dinheiro.',lens:'Economia através de uma civilização que está começando.',thumbnail:'/concept-atlas.png',url:'',createdAt:'2026-08-15T12:00:00Z',firstSeenAt:demoDate,observedAt:demoDate,videoCount:8,subscribers:18400,video:{id:'demo-v1',title:'What happens when everyone has more stones?',publishedAt:'2026-09-20T12:00:00Z',views:628400,duration:'PT8M42S',thumbnail:'/concept-atlas.png',url:''},status:'analyzed',evidence:['628.400 visualizações em uma observação às 48 horas — cenário fictício.','8 vídeos públicos e canal criado há 38 dias — cenário fictício.'],analysis:anatomy('Finanças'),demo:true},
 {id:'demo-orbit',name:'The Human Archive',handle:'@exemplo-archive',niche:'Tecnologia',language:'Inglês',format:'Long form · 3D',description:'Um curador alienígena investiga os objetos que mudaram a vida na Terra.',lens:'O presente visto como uma descoberta de outro planeta.',thumbnail:'/concept-atlas.png',url:'',createdAt:'2026-08-30T12:00:00Z',firstSeenAt:demoDate,observedAt:demoDate,videoCount:5,subscribers:9700,video:{id:'demo-v2',title:'Why did humans put their memories in a cloud?',publishedAt:'2026-09-20T18:00:00Z',views:512800,duration:'PT10M16S',thumbnail:'/concept-atlas.png',url:''},status:'new',evidence:['512.800 visualizações em uma observação às 42 horas — cenário fictício.','Canal de exemplo para explorar o fluxo de descoberta.'],demo:true},
 {id:'demo-cargo',name:'Starship Reserves',handle:'@exemplo-reserva',niche:'Finanças',language:'Inglês',format:'Long form · 2D',description:'Uma tripulação precisa fazer seus recursos durarem até o próximo planeta.',lens:'Decisões financeiras em uma viagem com recursos limitados.',thumbnail:'/concept-atlas.png',url:'',createdAt:'2026-08-20T12:00:00Z',firstSeenAt:demoDate,observedAt:demoDate,videoCount:11,subscribers:23100,video:{id:'demo-v3',title:'The ship that spent all its reserves',publishedAt:'2026-09-19T20:00:00Z',views:741200,duration:'PT7M54S',thumbnail:'/concept-atlas.png',url:''},status:'watching',evidence:['741.200 visualizações em uma observação às 64 horas — cenário fictício.','O cenário permite testar filtros de idioma e acompanhamento.'],demo:true}
];
export const demoManagedChannels: ManagedChannel[] = [
 {id:'managed-first-economy',name:'The First Economy',niche:'Finanças',format:'2D animation',stage:'production',priority:'high',description:'A village discovers money, debt and risk through survival decisions.',sourceChannelId:'demo-stone',opportunityId:'first-economy',createdAt:demoDate,updatedAt:demoDate},
 {id:'managed-human-archive',name:'The Human Archive',niche:'Tecnologia',format:'3D animation',stage:'research',priority:'normal',description:'An alien curator investigates the objects that changed human life.',sourceChannelId:'demo-orbit',createdAt:demoDate,updatedAt:demoDate}
];
export const demoData: RadarData = {mode:'demo',channels:demoChannels,channelStudies:[],gaps:[],managedChannels:demoManagedChannels,decisions:[],contexts:[],scripts:[],runs:[],settings:{...defaultSettings},integrations:[{id:'youtube',name:'YouTube',configured:false,detail:'Chave de pesquisa ainda não configurada.'},{id:'openai',name:'OpenAI',configured:false,detail:'Análises automáticas aguardam configuração.'},{id:'supabase',name:'Supabase',configured:false,detail:'Memória na nuvem aguardando conexão.'}],authenticated:false,authConfigured:false,lastUpdated:null,policyApproved:false};
