export type ChannelStudyComment = { text: string; likes: number; publishedAt: string };
export type ChannelStudySnapshot = { observedAt: string; views: number };
export type ChannelStudyVideo = { id: string; title: string; publishedAt: string; views: number; likes: number | null; commentCount: number | null; duration: string; thumbnail: string; url: string; comments: ChannelStudyComment[]; snapshots: ChannelStudySnapshot[]; velocity: { baseline: boolean; deltaViews: number | null; deltaHours: number | null; viewsPerHour: number | null } };
export type ChannelNicheProfile = { primaryNiche: string; subniche: string; audienceIntent: string; coreTopics: string[]; anchorTerms: string[]; excludedAdjacentTopics: string[]; searchQueries: string[]; formatSignature: string };
export type ChannelStudyTopicGenome = { winningEntities: string[]; recurringAngles: string[]; curiosityMechanisms: string[]; titleTokens: string[]; underperformingContrasts: string[] };
export type ChannelStudySustainability = { score: number; classification: 'fragile' | 'emerging' | 'repeatable'; rationale: string; supportingSignals: string[]; riskSignals: string[] };
export type ChannelStudyThumbnailAnalysis = { inspected: boolean; hitPatterns: string[]; weakPatterns: string[]; visualContrasts: string[]; compositionPatterns: string[]; textUsage: string[]; recurringSubjects: string[]; visualHooks: string[]; consistencySignals: string[]; limitations: string[] };
export type ChannelStudyCommentDemand = { requestedTopics: string[]; repeatedQuestions: string[]; confusionPoints: string[]; emotionalTriggers: string[]; objectionsAndDebates: string[] };
export type ChannelStudySequence = { hitVideoId: string; hitTitle: string; before: { id: string; title: string; views: number }[]; after: { id: string; title: string; views: number }[] };
export type ChannelStudyAnatomy = { executiveSummary: string; viralPatterns: string[]; titlePatterns: string[]; topicClusters: string[]; formatPatterns: string[]; commentSignals: string[]; audienceQuestions: string[]; repeatableMechanisms: string[]; oneOffRisks: string[]; contentGaps: string[]; productionNotes: string[]; commentDemand: ChannelStudyCommentDemand; topicGenome: ChannelStudyTopicGenome; sustainability: ChannelStudySustainability; sequenceInsights: string[]; weakVideoContrasts: string[]; limitations: string[] };
export type SimilarChannelMatch = { channel: Channel; similarityScore: number; similarityReason: string; matchedTerms: string[] };
export type ChannelStudy = { kind: 'channel-study'; id: string; input: string; topSampleScope?: 'global-search-candidates' | 'recent-uploads'; source: { id: string; name: string; handle: string; description: string; url: string; createdAt: string; videoCount: number; subscribers: number | null; avatar: string }; scannedVideos: number; totalPublicVideos: number; scanTruncated: boolean; comparisonSampleSize: number; topVideos: ChannelStudyVideo[]; thumbnailAnalysis: ChannelStudyThumbnailAnalysis; weakRecentVideos: ChannelStudyVideo[]; sequences: ChannelStudySequence[]; commentSampleSize: number; commentsAvailableVideos: number; nicheProfile: ChannelNicheProfile; anatomy: ChannelStudyAnatomy; similarCandidates: SimilarChannelMatch[]; metrics: { top10Views: number; top3Share: number; medianTop10Views: number; weakMedianViews: number | null; hitToWeakMedianRatio: number | null; videosAboveSubscribers: number | null; velocityTrackedVideos: number }; createdAt: string };
export type OpportunityCurve = {
 thesis: string;
 subject: string;
 promise: string;
 angle: string;
 narrativeMechanism: string;
 visualMechanism: string;
 emotionalDriver: string;
 repeatabilityEvidence: string[];
 failureConditions: string[];
};
export type OpportunitySignal = { level: 'low' | 'medium' | 'high' | 'uncertain'; rationale: string };
export type OpportunityValidation = {
 classification: 'hypothesis' | 'emerging' | 'structural';
 independentCreators: number;
 supportingVideos: number;
 evidence: string[];
 counterEvidence: string[];
 limitations: string[];
};
export type OpportunityTransfer = {
 id: string;
 label: string;
 principle: string;
 targetNiche: string;
 targetAudience: string;
 changedVariable: string;
 preservedMechanism: string;
 demandStatus: 'observed' | 'partial' | 'hypothesis';
 demandEvidence: string[];
 gap: string;
 whyItCouldWork: string;
 titles: string[];
 risks: string[];
};
export type OpportunityReport = {
 kind: 'opportunity-report';
 id: string;
 channelStudyId: string;
 sourceChannelId: string;
 title: string;
 thesis: string;
 curve: OpportunityCurve;
 validation: OpportunityValidation;
 saturation: {
  level: 'low' | 'medium' | 'high' | 'uncertain';
  rationale: string;
  saturatedPatterns: string[];
  underusedAngles: string[];
  whitespace: string[];
 };
 viralDNA: {
  demand: OpportunitySignal;
  repeatability: OpportunitySignal;
  breakout: OpportunitySignal;
  saturation: OpportunitySignal;
  gap: OpportunitySignal;
 };
 evidence: {
  topVideos: { id: string; title: string; views: number; url: string }[];
  similarChannels: { id: string; name: string; similarityScore: number; videoViews: number; url: string }[];
 };
 transfers: OpportunityTransfer[];
 channelConcept: {
  nameDirections: string[];
  positioning: string;
  audience: string;
  promise: string;
  format: string;
  thumbnailSystem: string;
  productionModel: string;
  firstEpisodes: string[];
  testPlan: string[];
 };
 nextMove: string;
 limitations: string[];
 createdAt: string;
};
export type Opportunity = { id: string; name: string; lens: string; promise: string; difference: string; episodes: string[]; risk: string; test: string; gap?: string; demandEvidence?: string[] };
export type GapOpportunity = { id: string; format: string; niche: string; status: 'investigate'; strength: number; rationale: string; directReferences: string[]; analogReferences: string[]; observedChannels: string[] };
export type Analysis = { observation: string; mechanism: string; hypotheses: string[]; gaps: string[]; limitations: string[]; opportunities: Opportunity[]; sources: { title: string; url: string }[]; review: string; createdAt: string };
export type Channel = { id: string; name: string; handle: string; niche: string; language: string; country?: string; format: string; description: string; lens: string; thumbnail: string; avatar?: string; url: string; createdAt: string; firstSeenAt: string; observedAt: string; videoCount: number; subscribers: number | null; video: { id: string; title: string; publishedAt: string; views: number; duration: string; thumbnail: string; url: string }; status: 'new' | 'watching' | 'analyzed' | 'archived'; evidence: string[]; analysis?: Analysis; demo?: boolean; discoverySource?: 'reference' | 'reference-adjacent'; reference?: { catalogName: string; tier: 'Legendary' | 'Really Good' | 'Reference'; format: string; niche: string } };
export type Decision = { id: string; channelId: string; opportunityId?: string; decision: 'approved' | 'rejected' | 'note'; reason: string; createdAt: string };
export type ResearchContext = { id: string; title: string; content: string; createdAt: string };
export type Script = { id: string; channelId: string; opportunityId: string; title: string; content: string; createdAt: string; status: 'draft' };
export type MissionBrief = {
 kind: 'mission-brief';
 id: string;
 objective: string;
 status: 'completed' | 'partial' | 'blocked';
 startedAt: string;
 completedAt: string;
 health: {
  supabase: boolean;
  youtube: boolean;
  openai: boolean;
  blockers: string[];
 };
 market: {
  qualifiedChannels: number;
  channelStudies: number;
  opportunityReports: number;
  productionReady: number;
  competitors?: number;
  competitorSignals?: number;
  competitorDna?: number;
  universeCurves?: number;
  universeGaps?: number;
  universeQueuePending?: number;
  universeQueueCompleted?: number;
 };
 workCompleted: string[];
 productionQueue: Array<{
  reportId: string;
  channelStudyId: string;
  sourceChannelId: string;
  title: string;
  sourceChannel: string;
  conceptName: string;
  firstEpisode: string;
  readiness: 'production-ready';
  reasons: string[];
  nextAction: string;
 }>;
 decisionsNeeded: Array<{
  type: 'pilot-decision' | 'evidence-review';
  title: string;
  reason: string;
  reportId?: string;
 }>;
 blockers: string[];
 notes: string[];
};
export type YouTubeSearchPurpose = 'reference-resolution' | 'radar-discovery' | 'channel-resolution' | 'channel-study' | 'similar-channels';
export type YouTubeSearchBudgetState = {
 kind: 'youtube-search-budget';
 id: string;
 pacificDate: string;
 limit: number;
 used: number;
 remaining: number;
 byPurpose: Record<YouTubeSearchPurpose,number>;
 purposeLimits: Record<YouTubeSearchPurpose,number>;
 duplicateSkips: number;
 blocked: boolean;
 blockedReason?: string;
 recentKeys: string[];
 updatedAt: string;
};
export type Run = { id: string; type: string; status: 'queued' | 'running' | 'completed' | 'failed'; startedAt: string; message: string };
export type UniverseCompetitorStatus = 'watch' | 'heating-up' | 'breakout' | 'pattern' | 'emerging-curve' | 'structural-curve' | 'gap-found' | 'production-reference';
export type UniverseSignal = {
 kind: 'breakout' | 'internal-outlier' | 'acceleration' | 'repeat-hit' | 'cadence-shift';
 strength: 'low' | 'medium' | 'high';
 title: string;
 evidence: string;
 observedAt: string;
};
export type UniverseCompetitorSnapshot = {
 observedAt: string;
 subscribers: number | null;
 videoCount: number;
 recentAverageViews: number | null;
 recentMedianViews: number | null;
 uploadsLast30d: number;
 strongestVideoId: string | null;
 strongestVideoViews: number | null;
};
export type UniverseChannelDNA = {
 generatedAt: string;
 summary: string;
 primaryNiche: string;
 subniche: string;
 audienceIntent: string;
 editorialPromise: string;
 formatSignature: string;
 contentPillars: string[];
 recurringEntities: string[];
 titlePatterns: string[];
 curiosityMechanisms: string[];
 emotionalDrivers: string[];
 differentiationSignals: string[];
 limitations: string[];
};
export type UniverseCompetitor = {
 kind: 'competitor';
 id: string;
 channelId: string;
 name: string;
 handle: string;
 url: string;
 avatar: string;
 country?: string;
 language: string;
 cluster: string;
 subniche: string;
 format: string;
 description: string;
 subscribers: number | null;
 videoCount: number;
 createdAt: string;
 importedAt: string;
 lastMonitoredAt: string;
 monitoringTier: 'hot' | 'active' | 'stable' | 'dormant';
 status: UniverseCompetitorStatus;
 recentAverageViews: number | null;
 recentMedianViews: number | null;
 recentVideoCount: number;
 uploadsLast30d: number;
 breakoutRatio: number | null;
 strongestRecentVideo: {
  id: string;
  title: string;
  publishedAt: string;
  views: number;
  duration: string;
  thumbnail: string;
  url: string;
 } | null;
 recentUploads: Array<{
  id: string;
  title: string;
  publishedAt: string;
  views: number;
  duration: string;
  thumbnail: string;
  url: string;
 }>;
 signals: string[];
 signalDetails?: UniverseSignal[];
 snapshots?: UniverseCompetitorSnapshot[];
 dna?: UniverseChannelDNA;
 dnaTags: string[];
 gapSummary?: string;
 updatedAt: string;
};
export type UniverseCurveClassification = 'hypothesis' | 'emerging' | 'structural';
export type UniverseCurve = {
 id: string;
 key: string;
 name: string;
 thesis: string;
 mechanismSteps: string[];
 supportingChannelIds: string[];
 independentCreators: number;
 classification: UniverseCurveClassification;
 clusters: string[];
 evidence: string[];
 counterEvidence: string[];
 recurringTitlePatterns: string[];
 transferableVariables: string[];
 limitations: string[];
};
export type UniverseGap = {
 id: string;
 curveId: string;
 title: string;
 targetSpace: string;
 preservedMechanism: string;
 changedVariable: string;
 demandStatus: 'observed' | 'partial' | 'hypothesis';
 targetEvidenceChannelIds: string[];
 demandEvidence: string[];
 sampleSaturation: 'low' | 'medium' | 'high' | 'uncertain';
 rationale: string;
 risks: string[];
 firstTests: string[];
};
export type UniverseImportQueueSummary = {
 total: number;
 pending: number;
 processing: number;
 completed: number;
 failed: number;
 retryable: number;
 progressPct: number;
};

export type UniverseMarketIntelligence = {
 kind: 'universe-market-intelligence';
 id: string;
 generatedAt: string;
 sourceCompetitorIds: string[];
 dnaCount: number;
 curves: UniverseCurve[];
 gaps: UniverseGap[];
 limitations: string[];
};
export type ManagedChannel = { id: string; name: string; niche: string; format: string; stage: 'idea' | 'research' | 'production' | 'published' | 'paused'; priority: 'high' | 'normal' | 'low'; description: string; sourceChannelId?: string; opportunityId?: string; createdAt: string; updatedAt: string };
export type Settings = { queries: string[]; languages: string[]; minViews: number; maxVideoAgeHours: number; maxChannelVideos: number; maxChannelAgeDays: number; enabled: boolean; autoAnalyze: boolean; maxAnalysesPerRun: number; analysisModel: string; scriptModel: string };
export type Integration = { id: string; name: string; configured: boolean; detail: string };
export type RadarData = { mode: 'demo' | 'live'; channels: Channel[]; universeCompetitors?: UniverseCompetitor[]; universeMarketIntelligence?: UniverseMarketIntelligence | null; universeQueue?: UniverseImportQueueSummary | null; channelStudies: ChannelStudy[]; opportunityReports?: OpportunityReport[]; missionBrief?: MissionBrief | null; youtubeSearchBudget?: YouTubeSearchBudgetState | null; gaps: GapOpportunity[]; managedChannels: ManagedChannel[]; decisions: Decision[]; contexts: ResearchContext[]; scripts: Script[]; runs: Run[]; settings: Settings; integrations: Integration[]; authenticated: boolean; authConfigured: boolean; lastUpdated: string | null; policyApproved: boolean };
export const defaultSettings: Settings = { queries: ['animated history', '3d animation engineering', 'animated storytelling', 'animated science explained', 'animated military history'], languages: ['en'], minViews: 500000, maxVideoAgeHours: 72, maxChannelVideos: 20, maxChannelAgeDays: 180, enabled: false, autoAnalyze: false, maxAnalysesPerRun: 6, analysisModel: 'gpt-5.6-terra', scriptModel: 'gpt-5.6-sol' };
