import test from 'node:test';
import assert from 'node:assert/strict';
import { authConfigured, createSession, validSession, sameOrigin, requireOperator } from '../src/lib/server/auth';
import { observedWithinWindow, settingsSchema } from '../src/lib/server/validation';
const now=Date.parse('2026-09-22T12:00:00Z');
test('missing secrets fail closed, signed sessions expire and reject tampering',()=>{process.env.APP_PASSWORD='';process.env.SESSION_SECRET='';assert.equal(authConfigured(),false);assert.equal(validSession('anything'),false);process.env.APP_PASSWORD='a'.repeat(24);process.env.SESSION_SECRET='b'.repeat(40);const session=createSession(now);assert.equal(validSession(session,now),true);assert.equal(validSession(session+'x',now),false);assert.equal(validSession(session,now+12*3600000),false);process.env.SESSION_SECRET='c'.repeat(40);assert.equal(validSession(session,now),false);delete process.env.APP_PASSWORD;delete process.env.SESSION_SECRET;});
test('writes require an authenticated session and exact origin',()=>{assert.equal(sameOrigin(new Request('https://radar.test/api/actions',{headers:{origin:'https://evil.test'}})),false);assert.throws(()=>requireOperator(new Request('https://radar.test/api/actions',{headers:{origin:'https://radar.test'}})),/senha/);assert.equal(sameOrigin(new Request('https://radar.test/api/actions')),false);});
test('viral window uses observation time, excluding exact 72h boundary and future publication',()=>{assert.equal(observedWithinWindow('2026-09-19T12:00:01Z','2026-09-22T12:00:00Z',500000,500000,72),true);assert.equal(observedWithinWindow('2026-09-19T12:00:00Z','2026-09-22T12:00:00Z',500000,500000,72),false);assert.equal(observedWithinWindow('2026-09-23T12:00:00Z','2026-09-22T12:00:00Z',500000,500000,72),false);assert.equal(observedWithinWindow('bad','bad',500000,500000,72),false);});
test('settings enforce bounded API, models and analysis budgets',()=>{const settings={queries:['finance'],languages:['en'],minViews:500000,maxVideoAgeHours:72,maxChannelVideos:20,maxChannelAgeDays:180,enabled:false,autoAnalyze:false,maxAnalysesPerRun:2,analysisModel:'gpt-5.6-terra',scriptModel:'gpt-5.6-sol'};assert.equal(settingsSchema.safeParse(settings).success,true);assert.equal(settingsSchema.safeParse({...settings,maxAnalysesPerRun:3}).success,false);assert.equal(settingsSchema.safeParse({...settings,queries:Array(6).fill('finance')}).success,false);assert.equal(settingsSchema.safeParse({...settings,minViews:-1}).success,false);assert.equal(settingsSchema.safeParse({...settings,analysisModel:'unknown-model'}).success,false);});
