import { z } from 'zod';
export const modelIds=['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'] as const;
export const modelSchema=z.enum(modelIds);
export const managedChannelSchema=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(2).max(100),niche:z.string().trim().min(2).max(80),format:z.string().trim().min(2).max(80),stage:z.enum(['idea','research','production','published','paused']),priority:z.enum(['high','normal','low']),description:z.string().trim().max(1000),sourceChannelId:z.string().max(100).optional(),opportunityId:z.string().max(150).optional()}).strict();
const shortList=(maxItems:number,maxLength=300)=>z.array(z.string().trim().min(1).max(maxLength)).max(maxItems);
export const channelBrainPayloadSchema=z.object({
 kind:z.literal('channel-brain'),
 channelId:z.string().uuid(),
 constitution:z.object({
  premise:z.string().trim().max(4000),
  audience:z.string().trim().max(2500),
  editorialPromise:z.string().trim().max(2500),
  worldview:z.string().trim().max(4000),
  tone:shortList(16,160),
  languageRules:shortList(30,500),
  humor:shortList(16,500),
  universeRules:shortList(30,500),
  forbidden:shortList(30,500),
  metaphors:shortList(30,500)
 }).strict(),
 characters:z.array(z.object({
  id:z.string().trim().min(1).max(80),
  name:z.string().trim().min(1).max(120),
  role:z.string().trim().max(600),
  traits:shortList(20,200),
  knows:shortList(60,300),
  doesNotKnow:shortList(60,300),
  rules:shortList(40,400)
 }).strict()).max(20),
 narrative:z.object({
  currentArc:z.string().trim().max(1000),
  stateSummary:z.string().trim().max(5000),
  lastEpisodeId:z.string().trim().max(180).optional(),
  establishedConcepts:shortList(120,300),
  partialConcepts:shortList(120,300),
  unknownConcepts:shortList(120,300),
  openThreads:shortList(120,600),
  resolvedThreads:shortList(120,600),
  doNotRepeat:shortList(120,600),
  nextConcepts:shortList(120,400)
 }).strict(),
 learnings:z.array(z.object({
  id:z.string().trim().min(1).max(120),
  type:z.enum(['audience','performance','editorial','production','operator']),
  statement:z.string().trim().min(1).max(1200),
  evidence:shortList(30,600),
  confidence:z.enum(['low','medium','high']),
  createdAt:z.string().datetime()
 }).strict()).max(300),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const contentArcSchema=z.object({
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 sequence:z.number().int().min(1).max(10000),
 status:z.enum(['planned','active','completed','paused']),
 name:z.string().trim().min(1).max(180),
 objective:z.string().trim().max(4000),
 premise:z.string().trim().max(4000),
 prerequisiteConcepts:shortList(100,120),
 targetConcepts:shortList(100,120),
 notes:shortList(100,600),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const channelEpisodeSchema=z.object({
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 arcId:z.string().uuid().optional(),
 sequence:z.number().int().min(1).max(100000),
 status:z.enum(['idea','planned','scripted','producing','published','archived']),
 title:z.string().trim().min(1).max(300),
 thesis:z.string().trim().max(5000),
 narrativeSummary:z.string().trim().max(5000),
 prerequisiteConcepts:shortList(100,120),
 introducesConcepts:shortList(100,120),
 reinforcesConcepts:shortList(100,120),
 opensThreads:shortList(100,600),
 resolvesThreads:shortList(100,600),
 repetitionKeys:shortList(100,300),
 youtubeVideoId:z.string().trim().max(120).optional(),
 publishedAt:z.string().datetime().optional(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const channelConceptSchema=z.object({
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 key:z.string().trim().regex(/^[a-z0-9][a-z0-9_-]{0,119}$/),
 label:z.string().trim().min(1).max(180),
 description:z.string().trim().max(3000),
 status:z.enum(['unknown','introduced','partial','established','retired']),
 prerequisiteKeys:shortList(100,120),
 introducedEpisodeId:z.string().uuid().optional(),
 establishedEpisodeId:z.string().uuid().optional(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const productionDnaPayloadSchema=z.object({
 kind:z.literal('production-dna'),
 channelId:z.string().uuid(),
 format:z.object({
  aspectRatio:z.string().trim().min(1).max(30),
  width:z.number().int().min(240).max(7680),
  height:z.number().int().min(240).max(4320),
  fps:z.number().int().min(1).max(120),
  targetDurationMinutes:z.object({
   min:z.number().min(0).max(360).nullable(),
   max:z.number().min(0).max(360).nullable()
  }).strict(),
  sceneDurationSeconds:z.object({
   min:z.number().min(0).max(600).nullable(),
   preferred:z.number().min(0).max(600).nullable(),
   max:z.number().min(0).max(600).nullable()
  }).strict()
 }).strict(),
 visual:z.object({
  styleName:z.string().trim().max(180),
  styleDescription:z.string().trim().max(5000),
  palette:shortList(40,120),
  compositionRules:shortList(80,500),
  cameraRules:shortList(80,500),
  motionRules:shortList(80,500),
  basePrompt:z.string().trim().max(12000),
  scenePromptTemplate:z.string().trim().max(12000),
  negativePrompt:z.string().trim().max(12000),
  forbidden:shortList(100,500)
 }).strict(),
 characters:z.array(z.object({
  id:z.string().trim().min(1).max(120),
  name:z.string().trim().min(1).max(180),
  description:z.string().trim().max(3000),
  visualRules:shortList(100,500),
  forbidden:shortList(100,500),
  referenceAssets:shortList(100,1000)
 }).strict()).max(30),
 voice:z.object({
  language:z.string().trim().max(80),
  providerPreference:shortList(20,120),
  voiceId:z.string().trim().max(250),
  voiceName:z.string().trim().max(250),
  narrationStyle:shortList(60,500),
  paceWpm:z.number().min(40).max(400).nullable(),
  pronunciationRules:shortList(100,500)
 }).strict(),
 captions:z.object({
  enabled:z.boolean(),
  styleDescription:z.string().trim().max(3000),
  position:z.string().trim().max(120),
  maxWordsPerCaption:z.number().int().min(1).max(30).nullable(),
  highlightKeywords:z.boolean()
 }).strict(),
 editing:z.object({
  transitions:shortList(50,160),
  defaultTransition:z.string().trim().max(160),
  kenBurns:z.boolean(),
  musicStyle:shortList(60,500),
  sfxRules:shortList(100,500),
  pacingRules:shortList(100,500)
 }).strict(),
 thumbnail:z.object({
  styleRules:shortList(100,500),
  forbidden:shortList(100,500)
 }).strict(),
 providers:z.object({
  image:shortList(30,160),
  video:shortList(30,160),
  voice:shortList(30,160),
  stock:shortList(30,160)
 }).strict(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const contentProjectPayloadSchema=z.object({
 kind:z.literal('content-project'),
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 episodeId:z.string().uuid(),
 opportunityId:z.string().trim().max(180).optional(),
 brief:z.object({
  theme:z.string().trim().max(1000),
  thesis:z.string().trim().max(5000),
  angle:z.string().trim().max(3000),
  promise:z.string().trim().max(3000),
  workingTitle:z.string().trim().max(300),
  thumbnailConcept:z.string().trim().max(4000),
  targetAudience:z.string().trim().max(3000),
  objective:z.string().trim().max(3000),
  previousEpisodeConnection:z.string().trim().max(3000),
  arcConnection:z.string().trim().max(3000)
 }).strict(),
 research:z.object({
  notes:z.string().trim().max(20000),
  sources:z.array(z.object({
   id:z.string().uuid(),
   title:z.string().trim().min(1).max(500),
   url:z.string().trim().url().max(3000),
   sourceType:z.enum(['primary','secondary','reference']),
   claim:z.string().trim().max(3000),
   checkedAt:z.string().datetime().optional()
  }).strict()).max(200),
  factChecks:z.array(z.object({
   id:z.string().uuid(),
   claim:z.string().trim().min(1).max(3000),
   status:z.enum(['unverified','supported','contradicted','needs-review']),
   sourceIds:z.array(z.string().uuid()).max(50),
   notes:z.string().trim().max(4000)
  }).strict()).max(200)
 }).strict(),
 approval:z.object({
  status:z.enum(['draft','ready','approved','blocked']),
  notes:z.string().trim().max(5000),
  approvedAt:z.string().datetime().optional(),
  approvedBy:z.string().trim().max(120).optional()
 }).strict(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const episodeScriptPayloadSchema=z.object({
 kind:z.literal('episode-script'),
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 episodeId:z.string().uuid(),
 contentProjectId:z.string().uuid(),
 title:z.string().trim().min(1).max(300),
 language:z.string().trim().min(2).max(80),
 sections:z.array(z.object({
  id:z.string().uuid(),
  label:z.string().trim().min(1).max(120),
  purpose:z.string().trim().max(1000),
  content:z.string().trim().min(1).max(40000)
 }).strict()).min(1).max(80),
 content:z.string().trim().min(1).max(200000),
 wordCount:z.number().int().min(1).max(50000),
 estimatedMinutes:z.number().min(0).max(600).nullable(),
 continuityNotes:shortList(100,1000),
 factCheckWarnings:shortList(100,1000),
 provenance:z.object({
  generatedBy:z.enum(['platform','chatgpt','codex','external','operator']),
  model:z.string().trim().max(120).optional()
 }).strict(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const transcriptPayloadSchema=z.object({
 kind:z.literal('transcript'),
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 episodeId:z.string().uuid(),
 scriptId:z.string().uuid(),
 voiceAssetId:z.string().uuid(),
 sourceType:z.enum(['alignment','scribe','imported']),
 languageCode:z.string().trim().max(30).optional(),
 text:z.string().trim().max(250000),
 words:z.array(z.object({
  id:z.string().uuid(),
  text:z.string().trim().min(1).max(1000),
  startSeconds:z.number().min(0).max(86400),
  endSeconds:z.number().min(0).max(86400),
  type:z.enum(['word','audio_event']),
  speakerId:z.string().trim().max(120).optional(),
  confidence:z.number().min(-100).max(1).optional()
 }).strict()).max(50000),
 segments:z.array(z.object({
  id:z.string().uuid(),
  startSeconds:z.number().min(0).max(86400),
  endSeconds:z.number().min(0).max(86400).nullable(),
  text:z.string().trim().min(1).max(10000),
  wordIds:z.array(z.string().uuid()).max(500)
 }).strict()).max(10000),
 scriptMatchScore:z.number().min(0).max(1).nullable(),
 scriptVersion:z.number().int().min(1).max(100000),
 voiceTake:z.number().int().min(1).max(100000),
 originalFormat:z.enum(['srt','vtt','txt','json']).optional(),
 provenance:z.object({
  provider:z.string().trim().max(120).optional(),
  model:z.string().trim().max(120).optional(),
  importedBy:z.literal('operator').optional()
 }).strict(),
 review:z.object({
  scriptMismatchOverride:z.boolean(),
  notes:z.string().trim().max(5000)
 }).strict(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const scenePlanPayloadSchema=z.object({
 kind:z.literal('scene-plan'),
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 episodeId:z.string().uuid(),
 scriptId:z.string().uuid(),
 voiceAssetId:z.string().uuid(),
 transcriptId:z.string().uuid(),
 transcriptVersion:z.number().int().min(1).max(100000),
 voiceTake:z.number().int().min(1).max(100000),
 audioDurationSeconds:z.number().min(0).max(86400),
 scenes:z.array(z.object({
  id:z.string().uuid(),
  sequence:z.number().int().min(1).max(100000),
  startSeconds:z.number().min(0).max(86400),
  endSeconds:z.number().min(0).max(86400),
  durationSeconds:z.number().min(0).max(86400),
  narration:z.string().trim().max(20000),
  transcriptSegmentIds:z.array(z.string().uuid()).max(200),
  transcriptWordIds:z.array(z.string().uuid()).max(2000),
  visualIntent:z.string().trim().max(5000),
  shotType:z.string().trim().max(500),
  characterIds:shortList(50,120),
  assetMode:z.enum(['image','video','stock','mixed','none']),
  promptDirection:z.string().trim().max(8000),
  notes:z.string().trim().max(4000)
 }).strict()).min(1).max(5000),
 review:z.object({
  notes:z.string().trim().max(5000),
  durationWarningsAccepted:z.boolean()
 }).strict(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const visualPromptSetPayloadSchema=z.object({
 kind:z.literal('visual-prompt-set'),
 id:z.string().uuid(),
 channelId:z.string().uuid(),
 episodeId:z.string().uuid(),
 scenePlanId:z.string().uuid(),
 scenePlanVersion:z.number().int().min(1).max(100000),
 productionDnaVersion:z.number().int().min(1).max(100000),
 styleLock:z.string().trim().max(16000),
 workflowStage:z.enum(['references','scenes','complete']),
 characterReferences:z.array(z.object({
  characterId:z.string().trim().min(1).max(120),
  refName:z.string().trim().regex(/^#[A-Za-z][A-Za-z0-9]*$/).max(120),
  prompt:z.string().trim().min(1).max(16000),
  sceneIds:z.array(z.string().uuid()).max(5000),
  assetReady:z.boolean()
 }).strict()).max(100),
 scenePrompts:z.array(z.object({
  sceneId:z.string().uuid(),
  sequence:z.number().int().min(1).max(100000),
  timecodeLabel:z.string().trim().regex(/^#\d+-\d{2}$/).max(20),
  startSeconds:z.number().min(0).max(86400),
  endSeconds:z.number().min(0).max(86400),
  characterIds:shortList(50,120),
  referenceNames:z.array(z.string().trim().regex(/^@[A-Za-z][A-Za-z0-9]*$/).max(120)).max(50),
  direction:z.string().trim().min(1).max(10000),
  prompt:z.string().trim().min(1).max(30000)
 }).strict()).max(5000),
 review:z.object({notes:z.string().trim().max(5000)}).strict(),
 createdAt:z.string().datetime(),
 updatedAt:z.string().datetime()
}).strict();
export const settingsSchema=z.object({queries:z.array(z.string().trim().min(2).max(100)).min(1).max(5),languages:z.tuple([z.literal('en')]),minViews:z.number().int().min(1000).max(1000000000),maxVideoAgeHours:z.number().int().min(1).max(168),maxChannelVideos:z.number().int().min(1).max(1000),maxChannelAgeDays:z.number().int().min(1).max(3650),enabled:z.boolean(),autoAnalyze:z.boolean(),maxAnalysesPerRun:z.number().int().min(0).max(12),analysisModel:modelSchema,scriptModel:modelSchema}).strict();
export function observedWithinWindow(publishedAt:string,observedAt:string,views:number,minViews:number,maxHours:number){ const age=Date.parse(observedAt)-Date.parse(publishedAt); return Number.isFinite(age)&&age>=0&&age<maxHours*3600000&&views>=minViews; }
