import 'server-only';
import type { Channel, Settings } from '@/lib/types';
import { checked, db, list, put } from './db';
import { HttpError } from './auth';
import { observedWithinWindow } from './validation';
import { providerSecret } from './providers';
type Item={id:string|{videoId:string};snippet:{channelId:string;title:string;description:string;publishedAt:string;customUrl?:string;defaultLanguage?:string;thumbnails?:Record<string,{url:string}>;resourceId?:{videoId:string}};statistics?:{viewCount?:string;videoCount?:string;subscriberCount?:string;hiddenSubscriberCount?:boolean};contentDetails?:{duration?:string;relatedPlaylists?:{uploads:string}}};
async function youtube(resource:string,params:Record<string,string>){const query=new URLSearchParams({...params,key:await providerSecret('youtube')});const response=await fetch(`https://www.googleapis.com/youtube/v3/${resource}?${query}`,{signal:AbortSignal.timeout(20000),cache:'no-store'});if(!response.ok)throw new HttpError(response.status===403?'YouTube recusou a consulta: confira a chave, API habilitada e cota.':`YouTube indisponível (HTTP ${response.status}).`,502);return (await response.json()).items as Item[];}
const thumb=(item:Item)=>item.snippet.thumbnails?.high?.url??item.snippet.thumbnails?.medium?.url??item.snippet.thumbnails?.default?.url??'';
export async function scan(config:Settings){const prior=await list<Channel>('radar_channels',100);const ids=new Set<string>();for(let i=0;i<config.queries.length;i++){const found=await youtube('search',{part:'snippet',type:'video',q:config.queries[i],order:'date',maxResults:'25',publishedAfter:new Date(Date.now()-config.maxVideoAgeHours*3600000).toISOString(),relevanceLanguage:config.languages[i%config.languages.length]});for(const item of found)if(typeof item.id!=='string')ids.add(item.id.videoId);}
// Bound tracked discovery to 20 channels per run; rotate daily to avoid starvation.
const offset=prior.length?Math.floor(Date.now()/86400000)*20%prior.length:0; const tracked=[...prior.slice(offset),...prior.slice(0,offset)].slice(0,20);
if(tracked.length){const cs=await youtube('channels',{part:'contentDetails',id:tracked.map(c=>c.id).join(',')});for(const c of cs){const uploads=c.contentDetails?.relatedPlaylists?.uploads;if(uploads){const videos=await youtube('playlistItems',{part:'snippet',playlistId:uploads,maxResults:'10'});for(const v of videos)if(v.snippet.resourceId)ids.add(v.snippet.resourceId.videoId);}}}
const candidates:Item[]=[];const idList=[...ids];for(let i=0;i<idList.length;i+=50)candidates.push(...await youtube('videos',{part:'snippet,statistics,contentDetails',id:idList.slice(i,i+50).join(',')}));
const observedAt=new Date().toISOString();const eligible=candidates.filter(v=>(!v.snippet.defaultLanguage||v.snippet.defaultLanguage.toLowerCase().startsWith('en'))&&observedWithinWindow(v.snippet.publishedAt,observedAt,Number(v.statistics?.viewCount??0),config.minViews,config.maxVideoAgeHours));const channelIds=[...new Set(eligible.map(v=>v.snippet.channelId))];const channels:Item[]=[];for(let i=0;i<channelIds.length;i+=50)channels.push(...await youtube('channels',{part:'snippet,statistics',id:channelIds.slice(i,i+50).join(',')}));let count=0;
for(const c of channels){const video=eligible.filter(v=>v.snippet.channelId===c.id).sort((a,b)=>Number(b.statistics?.viewCount)-Number(a.statistics?.viewCount))[0];if(!video)continue;const videoCount=Number(c.statistics?.videoCount??0),age=(Date.parse(observedAt)-Date.parse(c.snippet.publishedAt))/86400000;if(videoCount>config.maxChannelVideos||age>config.maxChannelAgeDays||age<0)continue;const id=c.id as string,old=prior.find(x=>x.id===id); const payload:Channel={id,name:c.snippet.title,handle:c.snippet.customUrl??'',niche:'A investigar',language:video.snippet.defaultLanguage??'Não informado',format:'A confirmar',description:c.snippet.description.slice(0,2000),lens:old?.lens??'Perspectiva aguardando investigação',thumbnail:thumb(video),avatar:thumb(c),url:`https://www.youtube.com/channel/${id}`,createdAt:c.snippet.publishedAt,firstSeenAt:old?.firstSeenAt??observedAt,observedAt,videoCount,subscribers:c.statistics?.hiddenSubscriberCount?null:Number(c.statistics?.subscriberCount??0),video:{id:video.id as string,title:video.snippet.title,publishedAt:video.snippet.publishedAt,views:Number(video.statistics?.viewCount??0),duration:video.contentDetails?.duration??'',thumbnail:thumb(video),url:`https://www.youtube.com/watch?v=${video.id}`},status:old?.status??'new',evidence:[`Visualizações públicas observadas em ${observedAt}.`,`Publicado em ${video.snippet.publishedAt}; não há histórico anterior ao primeiro registro.`,`Formato não inferido apenas pela duração; RPM e retenção indisponíveis.`],...(old?.video.id===video.id&&old.analysis?{analysis:old.analysis}:{})};await put('radar_channels',id,payload);checked(await db().from('radar_snapshots').insert({channel_id:id,video_id:video.id,views:payload.video.views,observed_at:observedAt}));count++;}return count;
}

