import { z } from 'zod';
import { requireOperator, errorResponse, HttpError } from '@/lib/server/auth';
import { channel, dbConfigured, put } from '@/lib/server/db';
import { runAiJob } from '@/lib/server/ai-job';
import { analyze, writeScript } from '@/lib/server/ai';
import { runRadar } from '@/lib/server/jobs';
import { runChannelStudy } from '@/lib/server/channel-study';
import { managedChannelSchema, settingsSchema } from '@/lib/server/validation';
export const runtime='nodejs';
export const maxDuration=300;
const schema=z.object({action:z.enum(['scan','analyze','decision','context','settings','script','managedChannel','channelStudy']),channelId:z.string().max(100).optional(),opportunityId:z.string().max(150).optional(),reason:z.string().trim().min(1).max(4000).optional(),decision:z.enum(['approved','rejected','note']).optional(),title:z.string().trim().min(1).max(200).optional(),content:z.string().trim().min(1).max(20000).optional(),settings:settingsSchema.optional(),managedChannel:managedChannelSchema.optional(),channelInput:z.string().trim().min(2).max(500).optional()}).strict();
export async function POST(request:Request){try{requireOperator(request);if(!dbConfigured())throw new HttpError('O modo demonstração não executa pesquisas. Configure o Supabase.',503);if(Number(request.headers.get('content-length')??0)>30000)throw new HttpError('Solicitação muito extensa.',413);const parsed=schema.safeParse(await request.json());if(!parsed.success)throw new HttpError('Confira os campos enviados e os limites de configuração.');const body=parsed.data;let message='Informações salvas.';switch(body.action){case 'scan':message=await runRadar();break;case 'settings':if(!body.settings)throw new HttpError('Configurações ausentes.');await put('radar_settings','main',body.settings);message='Configurações salvas. A rotina depende de um agendador configurado.';break;case 'managedChannel':if(!body.managedChannel)throw new HttpError('Informe os dados do canal.');{const now=new Date().toISOString(),id=body.managedChannel.id??crypto.randomUUID();await put('radar_managed_channels',id,{...body.managedChannel,id,createdAt:now,updatedAt:now});message='Canal salvo na operação.';}break;case 'channelStudy':if(!body.channelInput)throw new HttpError('Informe o canal que deseja analisar.');await runAiJob('channel-study',body.channelInput.slice(0,120),()=>runChannelStudy(body.channelInput!));message='Análise profunda concluída: top vídeos, comentários, Niche Lock e canais similares processados.';break;case 'context':if(!body.title||!body.content)throw new HttpError('Informe título e contexto.');{const id=crypto.randomUUID();await put('radar_contexts',id,{id,title:body.title,content:body.content,createdAt:new Date().toISOString()});}break;default:{if(!body.channelId)throw new HttpError('Escolha um canal.');const c=await channel(body.channelId);if(body.action==='analyze'){await runAiJob('analyze',c.video.id,()=>analyze(c));message='Anatomia parcial e cinco oportunidades preparadas.';}else if(body.action==='script'){if(!body.opportunityId)throw new HttpError('Escolha uma oportunidade.');await runAiJob('script',c.video.id+':'+body.opportunityId,()=>writeScript(c,body.opportunityId!));message='Rascunho salvo. As verificações factuais indicadas ainda são necessárias.';}else{if(!body.decision||!body.reason)throw new HttpError('Informe a decisão e seu motivo.');if(body.opportunityId&&!c.analysis?.opportunities.some(o=>o.id===body.opportunityId))throw new HttpError('Oportunidade não encontrada.');const id=crypto.randomUUID();await put('radar_decisions',id,{id,channelId:c.id,opportunityId:body.opportunityId,decision:body.decision,reason:body.reason,createdAt:new Date().toISOString()});}}}return Response.json({message});}catch(e){return errorResponse(e);}}
