'use client';

import { useMemo, useState } from 'react';
import { BrainCircuit, Check, CircleDot, Film, FolderKanban, Layers3, Plus, Sparkles } from 'lucide-react';
import type { Channel, ChannelBrain, ManagedChannel, Opportunity } from '@/lib/types';

const stages:Record<ManagedChannel['stage'],string>={idea:'Ideia',research:'Em pesquisa',production:'Em produção',published:'Publicado',paused:'Pausado'};
const priorities:Record<ManagedChannel['priority'],string>={high:'Alta prioridade',normal:'Prioridade normal',low:'Baixa prioridade'};
type Draft=Omit<ManagedChannel,'id'|'createdAt'|'updatedAt'>;
const empty=():Draft=>({name:'',niche:'Finanças',format:'2D animation',stage:'idea',priority:'normal',description:''});

export default function ChannelManagement({items,brains,radarChannels,demo,onSave,onMessage,onOpenBrain}:{items:ManagedChannel[];brains:ChannelBrain[];radarChannels:Channel[];demo:boolean;onSave:(channel:ManagedChannel)=>void;onMessage:(message:string)=>void;onOpenBrain:(channel:ManagedChannel)=>void}){
 const [draft,setDraft]=useState<Draft>(empty),[showForm,setShowForm]=useState(false),[filter,setFilter]=useState<'all'|ManagedChannel['stage']>('all');
 const visible=useMemo(()=>filter==='all'?items:items.filter(item=>item.stage===filter),[filter,items]);
 const brainByChannel=useMemo(()=>new Map(brains.map(brain=>[brain.channelId,brain])),[brains]);
 const opportunities=radarChannels.flatMap(channel=>(channel.analysis?.opportunities??[]).map(opportunity=>({channel,opportunity})));
 function save(event:React.FormEvent){event.preventDefault();if(!draft.name.trim()){onMessage('Dê um nome ao canal antes de salvar.');return;}const now=new Date().toISOString();onSave({id:crypto.randomUUID(),...draft,name:draft.name.trim(),description:draft.description.trim(),createdAt:now,updatedAt:now});setDraft(empty());setShowForm(false);}
 function addFromOpportunity(channel:Channel,opportunity:Opportunity){const now=new Date().toISOString();onSave({id:crypto.randomUUID(),name:opportunity.name,niche:channel.niche,format:channel.format.split(' · ')[1]??channel.format,stage:'idea',priority:'normal',description:opportunity.lens,sourceChannelId:channel.id,opportunityId:opportunity.id,createdAt:now,updatedAt:now});}
 return <>
  <section className="channel-management-hero"><div><div className="eyebrow">PORTFÓLIO EDITORIAL</div><h2>Seus canais.<br/><span>Uma operação com foco.</span></h2><p>Transforme descobertas em canais ativos, com contexto, estágio e próxima prioridade visíveis.</p></div><div className="portfolio-metrics"><div><span>EM PRODUÇÃO</span><strong>{items.filter(item=>item.stage==='production').length}</strong></div><div><span>EM PESQUISA</span><strong>{items.filter(item=>item.stage==='research').length}</strong></div><div><span>PUBLICADOS</span><strong>{items.filter(item=>item.stage==='published').length}</strong></div></div></section>
  <section className="channel-management-toolbar"><div className="segmented" aria-label="Filtrar canais da operação">{([['all','Todos'],['idea','Ideias'],['research','Pesquisa'],['production','Produção'],['published','Publicados']] as const).map(([id,label])=><button key={id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><button className="button primary" onClick={()=>setShowForm(!showForm)}><Plus size={17}/>{showForm?'Fechar cadastro':'Novo canal'}</button></section>
  {showForm&&<section className="panel channel-form"><div className="panel-heading"><FolderKanban size={20}/><h2>Cadastrar canal</h2></div><form onSubmit={save}><div className="form-grid"><label>Nome do canal <small>Em inglês, pois é o nome voltado ao público.</small><input autoFocus value={draft.name} maxLength={100} onChange={event=>setDraft({...draft,name:event.target.value})} placeholder="Ex.: The First Economy"/></label><label>Nicho<input value={draft.niche} maxLength={80} onChange={event=>setDraft({...draft,niche:event.target.value})}/></label><label>Formato<select value={draft.format} onChange={event=>setDraft({...draft,format:event.target.value})}><option>2D animation</option><option>3D animation</option><option>Long form</option><option>Shorts</option><option>Documentary</option></select></label><label>Estágio<select value={draft.stage} onChange={event=>setDraft({...draft,stage:event.target.value as ManagedChannel['stage']})}>{Object.entries(stages).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Prioridade<select value={draft.priority} onChange={event=>setDraft({...draft,priority:event.target.value as ManagedChannel['priority']})}>{Object.entries(priorities).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><label>Proposta e contexto<textarea rows={3} maxLength={1000} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})} placeholder="Qual é a promessa editorial deste canal?"/></label><button className="button primary"><Check size={17}/>Adicionar ao portfólio</button></form></section>}
  <section className="managed-channel-grid">{visible.map(item=>{const brain=brainByChannel.get(item.id);return <article className="managed-channel-card" key={item.id}><div className="managed-card-top"><span className={`managed-icon ${item.stage}`}><Film size={20}/></span><select aria-label={`Estágio de ${item.name}`} value={item.stage} onChange={event=>onSave({...item,stage:event.target.value as ManagedChannel['stage'],updatedAt:new Date().toISOString()})}>{Object.entries(stages).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div><h2>{item.name}</h2><p>{item.description||'Contexto editorial ainda não registrado.'}</p></div><div className="managed-meta"><span>{item.niche}</span><span>{item.format}</span>{brain&&<span className="brain-version-chip">Brain v{brain.version}</span>}</div><div className="managed-card-footer"><span className={`priority priority-${item.priority}`}><CircleDot size={13}/>{priorities[item.priority]}</span><span>{item.opportunityId?'Vinculado a uma oportunidade':'Canal independente'}</span></div><button className="managed-brain-button" onClick={()=>onOpenBrain(item)}><BrainCircuit size={16}/><span>{brain?`Abrir Channel Brain v${brain.version}`:'Criar Channel Brain'}</span></button></article>})}</section>
  {!visible.length&&<div className="empty-state"><span className="empty-icon"><FolderKanban size={30}/></span><h3>Nenhum canal neste estágio</h3><p>Cadastre um canal ou transforme uma perspectiva do radar em uma iniciativa editorial.</p></div>}
  <section className="channel-source-panel"><div className="panel-heading"><Sparkles size={20}/><h2>Perspectivas prontas para virar canal</h2></div><p>Estas propostas vêm da anatomia de referências do radar. Escolha apenas as que fazem sentido para seu portfólio.</p><div className="source-opportunities">{opportunities.slice(0,5).map(({channel,opportunity})=><article key={opportunity.id}><span className="tag orange">{channel.niche}</span><h3>{opportunity.name}</h3><p>{opportunity.lens}</p><button className="button subtle small" onClick={()=>addFromOpportunity(channel,opportunity)}><Layers3 size={15}/>Adicionar ao portfólio</button></article>)}</div>{demo&&<p className="demo-source-note">As propostas desta demonstração são fictícias e servem apenas para explorar o fluxo da plataforma.</p>}</section>
 </>;
}
