import { demoData } from '@/lib/demo';
import { authenticated, authConfigured, errorResponse } from '@/lib/server/auth';
import { dbConfigured, loadRadar, policyApproved } from '@/lib/server/db';
import { providerStatuses } from '@/lib/server/providers';
import { loadYouTubeSearchBudget } from '@/lib/server/youtube-search-budget';
import { universeQueueSummary } from '@/lib/server/universe';
import { hydrateMissionBriefUniverse } from '@/lib/mission';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const auth=authenticated(request);let configured={openai:!!process.env.OPENAI_API_KEY,youtube:!!process.env.YOUTUBE_API_KEY,elevenlabs:!!process.env.ELEVENLABS_API_KEY,googleai:!!process.env.GOOGLE_AI_API_KEY,pexels:!!process.env.PEXELS_API_KEY,pixabay:!!process.env.PIXABAY_API_KEY};if(auth&&dbConfigured()){try{const statuses=await providerStatuses();configured={openai:!!statuses.find(x=>x.provider==='openai')?.configured,youtube:!!statuses.find(x=>x.provider==='youtube')?.configured,elevenlabs:!!statuses.find(x=>x.provider==='elevenlabs')?.configured,googleai:!!statuses.find(x=>x.provider==='googleai')?.configured,pexels:!!statuses.find(x=>x.provider==='pexels')?.configured,pixabay:!!statuses.find(x=>x.provider==='pixabay')?.configured};}catch{}}const integrations=[{id:'youtube',name:'YouTube Data API',configured:configured.youtube,detail:'Descoberta e estatísticas públicas.'},{id:'supabase',name:'Supabase',configured:dbConfigured(),detail:'Memória privada da operação.'},{id:'openai',name:'OpenAI',configured:configured.openai,detail:'Pesquisa assistida, inteligência e roteiros.'},{id:'elevenlabs',name:'ElevenLabs',configured:configured.elevenlabs,detail:'Narração e vozes do Voice Engine.'},{id:'googleai',name:'Google AI',configured:configured.googleai,detail:'Nano Banana e Veo para geração visual.'},{id:'pexels',name:'Pexels',configured:configured.pexels,detail:'Stock photos e vídeos.'},{id:'pixabay',name:'Pixabay',configured:configured.pixabay,detail:'Stock images e vídeos.'}];const flags={authenticated:auth,authConfigured:authConfigured(),policyApproved:policyApproved(),integrations};if(auth&&dbConfigured()){const [radar,youtubeSearchBudget,universeQueue]=await Promise.all([loadRadar(),loadYouTubeSearchBudget(),universeQueueSummary()]);const missionBrief=hydrateMissionBriefUniverse(radar.missionBrief,radar.universeCompetitors,radar.universeMarketIntelligence,universeQueue);return Response.json({...radar,missionBrief,youtubeSearchBudget,universeQueue,...flags,mode:'live'},{headers:{'Cache-Control':'no-store'}});}return Response.json({...demoData,...flags,mode:'demo'},{headers:{'Cache-Control':'no-store'}});}catch(e){return errorResponse(e);}}
